[package]
name = 'wasmer/winterjs'
version = '0.2.1'
description = 'The JavaScript runtime that brings JavaScript to Wasmer Edge.'
license = 'MIT'
readme = 'README.md'
repository = 'https://github.com/wasmerio/winterjs/'
entrypoint = 'winterjs'

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[dependencies]

[[module]]
name = 'winterjs'
source = 'target/wasm32-wasmer-wasi/release/winterjs.wasm'
abi = 'wasi'

[[command]]
name = 'winterjs'
module = 'winterjs'

[[command]]
name = 'wasmer-winter'
module = 'winterjs'
