name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: OS Setup (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3.11 python3-distutils llvm-15 libclang-dev clang-15
          npm i -g wasm-opt
          sudo rm /usr/bin/clang
          sudo rm /usr/bin/clang++
          sudo ln -s /usr/bin/clang-15 /usr/bin/clang
          sudo ln -s /usr/bin/clang++-15 /usr/bin/clang++
          sudo ln -s /usr/bin/llvm-ar-15 /usr/bin/llvm-ar
          sudo ln -s /usr/bin/llvm-nm-15 /usr/bin/llvm-nm
          sudo ln -s /usr/bin/llvm-ranlib-15 /usr/bin/llvm-ranlib

      - name: Tool Versions
        run: |
          echo clang
          clang -v
          echo '####################'
          echo llvm-ar
          llvm-ar -v
          echo '####################'
          echo llvm-nm
          llvm-nm -v
          echo '####################'
          echo llvm-ranlib
          llvm-ranlib -v
          echo '####################'
          echo wasm-opt
          wasm-opt --version
          echo '####################'
          echo python
          python3.11 -V

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.76"
          components: "clippy,rustfmt"

      - name: Download wasix-libc
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          repo: wasix-org/rust
          file: wasix-libc.tar.gz
          target: sysroot/wasix-libc.tar.gz

      - name: Unpack wasix-libc
        run: |
          cd sysroot
          tar xzf wasix-libc.tar.gz

      - name: Download wasix toolchain
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          repo: wasix-org/rust
          file: rust-toolchain-x86_64-unknown-linux-gnu.tar.gz
          target: wasix-rust-toolchain/toolchain.tar.gz

      - name: Install wasix toolchain
        run: |
          cd wasix-rust-toolchain
          tar xzf toolchain.tar.gz
          chmod +x bin/*
          chmod +x lib/rustlib/x86_64-unknown-linux-gnu/bin/*
          chmod +x lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld/*
          rustup toolchain link wasix .

      - name: Build
        run: |
          export WASI_SYSROOT=$(pwd)/sysroot/wasix-libc/sysroot32
          bash build.sh

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: winterjs-wasm
          path: target/wasm32-wasmer-wasi/release/winterjs.wasm
