name: Build

on:
  workflow_call:

jobs:
  build-libc:
    runs-on: ubuntu-latest
    steps:
      - name: show git config
        run: |
          env
          cat ~/.config/git/config || true
          cat ~/.gitconfig || true
          ls -lha ./wasix-libc || true

      - name: Check out wasix-libc
        uses: actions/checkout@v3
        with:
          repository: wasix-org/wasix-libc
          ref: main
          path: wasix-libc
          submodules: "recursive"

      - name: OS Setup (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl wget xz-utils git python3 llvm lld
          ln -s /usr/bin/llvm-ar

      - name: Build wasix-libc
        run: |
          cd wasix-libc
          ./build32.sh
          ls
          ls sysroot32

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: wasix-libc
          path: wasix-libc/sysroot32

  build:
    needs: build-libc
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Download wasix-libc
        uses: actions/download-artifact@v3
        with:
          name: wasix-libc
          path: wasix-libc

      - name: ls
        run: |
          ls
          ls wasix-libc
