name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: OS Setup (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3.11 python3-distutils llvm libclang-dev clang

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.76"
          components: "clippy,rustfmt"

      - name: Download wasix-libc
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          repo: wasix-org/rust
          file: wasix-libc.tar.gz
          target: wasix-libc/wasix-libc.tar.gz

      - name: Download wasix toolchain
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          repo: wasix-org/rust
          file: rust-toolchain-x86_64-unknown-linux-gnu.tar.gz
          target: wasix-rust-toolchain/toolchain.tar.gz

      - name: Install wasix toolchain
        run: |
          cd wasix-rust-toolchain
          tar xzf toolchain.tar.gz
          chmod +x bin/*
          rustup toolchain link wasix .

      - name: Download wasix-libc
        uses: actions/download-artifact@v3
        with:
          name: wasix-libc
          path: sysroot

      - name: Build
        run: |
          export WASI_SYSROOT=$(pwd)/sysroot
          bash build.sh

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: winterjs-wasm
          path: target/wasm32-wasmer-wasi/release/winterjs.wasm
