name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: OS Setup (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3.11 python3-distutils llvm-15 libclang-dev clang-15 wabt
          npm i -g wasm-opt pnpm concurrently
          sudo rm /usr/bin/clang
          sudo rm /usr/bin/clang++
          sudo ln -s /usr/bin/clang-15 /usr/bin/clang
          sudo ln -s /usr/bin/clang++-15 /usr/bin/clang++
          sudo ln -s /usr/bin/llvm-ar-15 /usr/bin/llvm-ar
          sudo ln -s /usr/bin/llvm-nm-15 /usr/bin/llvm-nm
          sudo ln -s /usr/bin/llvm-ranlib-15 /usr/bin/llvm-ranlib

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.76"
          components: "clippy,rustfmt"

      - name: Setup Wasmer
        uses: wasmerio/setup-wasmer@v3.1

      - name: build test suite JS app
        run: |
          cd test-suite/js-test-app
          pnpm i
          pnpm run build

      # - name: Download artifacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     path: build-artifacts

      - name: Run API test suite
        run: |
          conc --kill-others --success "command-1" \
            "wasmer run build-artifacts/winterjs-wasm/winterjs.wasm --net --mapdir /app:./test-suite/js-test-app/dist -- serve /app/bundle.js" \
            "sleep 10 && cd test-suite && cargo run"
